services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    volumes:
      - ./src:/var/www
    environment:
      - MEDUSA_WEBHOOK_SECRET='Wp7WCBqjZ3R6qdIix/lm3fsVjgU5aqs4mThbNmiZk1g='
    depends_on:
      - db
      - redis
    networks:
      - laravel
      - shared-network 

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
      - shared-network  # Agregar red compartida

  queue-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-worker
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - ./src:/var/www
    depends_on:
      - app
      - redis
    networks:
      - laravel
      - shared-network  # Agregar red compartida

  db:
    image: postgres:16
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5435:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6381:6379"
    networks:
      - laravel

networks:
  laravel:
  shared-network:
    external: true  # Red externa compartida

volumes:
  dbdata: